/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.view;

import BL.DepartmentiRepository;
import BL.EmployeeException;
import BL.PerdoruesiRepository;
import BL.PunetoriRepository;
import DAL.Roli;
import BL.TelefoniRepository;
import BL.TitulliRepository;
import DAL.Departmenti;
import DAL.Perdoruesi;
import DAL.Punetori;
import static DAL.Punetori_.perdoruesi;
import DAL.Telefoni;
import DAL.TitulliPunetorit;
import gui.model.DepartmentiComboBoxModel;
import gui.model.PunetoriTableModel;
import gui.model.TitulliComboBoxModel;
import java.awt.Color;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author MR-ROBOT
 */
public class PunetoriForm extends javax.swing.JInternalFrame {

    PunetoriRepository pr = new PunetoriRepository();
    TelefoniRepository tr = new TelefoniRepository();
    PunetoriTableModel ptm = new PunetoriTableModel();
    DepartmentiComboBoxModel dcb = new DepartmentiComboBoxModel();
    DepartmentiRepository dr = new DepartmentiRepository();
    PerdoruesiRepository perdoruesiRepository = new PerdoruesiRepository();
    TitulliComboBoxModel tcbm = new TitulliComboBoxModel();
    TitulliRepository titulliRepository = new TitulliRepository();

    /**
     * Creates new form PunetoriForm
     */
    public PunetoriForm() {
        initComponents();
        loadComboBox();
        tabelaSelectedIndexChange();
        loadTable();
        this.setSize(1400, 800);
        this.setResizable(true);
        table.setAutoCreateRowSorter(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        punetoriIdTxt = new javax.swing.JTextField();
        datalindjes = new com.toedter.calendar.JDateChooser();
        emriTxt = new javax.swing.JTextField();
        mbiemriTxt = new javax.swing.JTextField();
        emailTxt = new javax.swing.JTextField();
        mashkullRadio = new javax.swing.JRadioButton();
        femerRadio = new javax.swing.JRadioButton();
        departmentiCB = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        pozitaCB = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        adresaTxt = new javax.swing.JTextField();
        biznisTelTxt = new javax.swing.JTextField();
        homeTxt = new javax.swing.JTextField();
        datapunesimit = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        qytetiTxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        telMobilTxt = new javax.swing.JTextField();
        usernameTxt = new javax.swing.JTextField();
        passTxt = new javax.swing.JPasswordField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        roliCB = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setClosable(true);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.setGridColor(new java.awt.Color(0, 0, 0));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        table.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tablePropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 2));

        jTabbedPane1.setBackground(new java.awt.Color(0, 204, 0));

        jLabel1.setText("PunetoriID:");

        jLabel2.setText("Emri:");

        jLabel3.setText("Mbiemri");

        jLabel5.setText("Gjinia:");

        jLabel6.setText("Email:");

        jLabel8.setText("Data Lindjes:");

        punetoriIdTxt.setEditable(false);
        punetoriIdTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                punetoriIdTxtActionPerformed(evt);
            }
        });

        emriTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emriTxtActionPerformed(evt);
            }
        });

        mbiemriTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbiemriTxtActionPerformed(evt);
            }
        });

        emailTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTxtActionPerformed(evt);
            }
        });

        mashkullRadio.setText("Mashkull");
        mashkullRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mashkullRadioActionPerformed(evt);
            }
        });

        femerRadio.setText("Femer");
        femerRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femerRadioActionPerformed(evt);
            }
        });

        departmentiCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                departmentiCBItemStateChanged(evt);
            }
        });
        departmentiCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentiCBActionPerformed(evt);
            }
        });
        departmentiCB.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                departmentiCBPropertyChange(evt);
            }
        });

        jLabel14.setText("Departmenti");

        jLabel18.setText("Pozita");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(65, 65, 65)
                        .addComponent(punetoriIdTxt))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(98, 98, 98)
                        .addComponent(emriTxt))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(83, 83, 83)
                        .addComponent(mbiemriTxt))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(datalindjes, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(mashkullRadio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(femerRadio)
                                .addGap(36, 36, 36))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(93, 93, 93)
                        .addComponent(emailTxt))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel18))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pozitaCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(departmentiCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1))
                    .addComponent(punetoriIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(emriTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mbiemriTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(femerRadio, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mashkullRadio)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(datalindjes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(departmentiCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pozitaCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Te dhenat Kresore", jPanel1);

        jLabel9.setText("Adresa");

        jLabel10.setText("Data Punesimit");

        jLabel7.setText("Tel-Shtepise");

        jLabel11.setText("Tel-Biznis");

        adresaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adresaTxtActionPerformed(evt);
            }
        });

        biznisTelTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biznisTelTxtActionPerformed(evt);
            }
        });

        homeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeTxtActionPerformed(evt);
            }
        });

        jLabel12.setText("Qyteti");

        qytetiTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qytetiTxtActionPerformed(evt);
            }
        });

        jLabel13.setText("TEL MOBIL:");

        telMobilTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telMobilTxtActionPerformed(evt);
            }
        });

        usernameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTxtActionPerformed(evt);
            }
        });

        jLabel15.setText("Passwod");

        jLabel16.setText("Username");

        roliCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Punetor", "Menaxher" }));

        jLabel17.setText("Roli");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(78, 78, 78)
                        .addComponent(qytetiTxt))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(71, 71, 71)
                        .addComponent(adresaTxt))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11)
                            .addComponent(jLabel7))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(homeTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(biznisTelTxt)
                            .addComponent(telMobilTxt)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(roliCB, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(passTxt)
                                .addComponent(usernameTxt)
                                .addComponent(datapunesimit, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(homeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(biznisTelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel13))
                    .addComponent(telMobilTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel12))
                    .addComponent(qytetiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel9))
                    .addComponent(adresaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(datapunesimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roliCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(27, 27, 27))
        );

        jTabbedPane1.addTab("Te dhena te tjera", jPanel4);

        deleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img.icon/delete_1.png"))); // NOI18N
        deleteBtn.setText("Fshij");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        saveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img.icon/save-button.png"))); // NOI18N
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Anulo");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(saveBtn)
                .addGap(40, 40, 40)
                .addComponent(deleteBtn)
                .addGap(44, 44, 44)
                .addComponent(cancelBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteBtn)
                    .addComponent(saveBtn)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void punetoriIdTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_punetoriIdTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_punetoriIdTxtActionPerformed

    private void emriTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emriTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emriTxtActionPerformed

    private void adresaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adresaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adresaTxtActionPerformed

    private void biznisTelTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biznisTelTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_biznisTelTxtActionPerformed

    private void mbiemriTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbiemriTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mbiemriTxtActionPerformed

    private void homeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homeTxtActionPerformed

    private void emailTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTxtActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        try {
            int row = table.getSelectedRow();
            if (row == -1) { //nuk kemi selektuar asgje
                if (CheckMismatchType() && fieldsValidation()) {

                    Punetori p = new Punetori();
                    Telefoni t = new Telefoni();
                    Perdoruesi perdoruesi = new Perdoruesi();
                    p.setEmri(emriTxt.getText());
                    p.setMbiemri(mbiemriTxt.getText());
                    p.setDataLindjes(datalindjes.getDate());
                    p.setQyteti(qytetiTxt.getText());
                    p.setDataPunesimit(datapunesimit.getDate());
                    p.setAdresa(adresaTxt.getText());
                    p.setEmail(emailTxt.getText());
                    p.setDepartmentiId((Departmenti) departmentiCB.getSelectedItem());
                    t.setTelefoniShtepise(homeTxt.getText());
                    t.setTelefoniBiznesit(biznisTelTxt.getText());
                    t.setTelefoniMobil(telMobilTxt.getText());
                    t.setPunetoriId(p);
                    p.setTitulli((TitulliPunetorit) pozitaCB.getSelectedItem());

                    // Create list and add telefoni
                    List<Telefoni> numrat = new ArrayList<>();
                    numrat.add(t);
                    p.setTelefoniCollection(numrat);
                    t.setPunetoriId(p);
                    if (mashkullRadio.isSelected()) {
                        p.setGjinia("M");
                        mashkullRadio.setSelected(true);
                        femerRadio.setSelected(false);
                    } else if (femerRadio.isSelected()) {
                        p.setGjinia("F");
                        mashkullRadio.setSelected(false);
                        femerRadio.setSelected(true);
                    }
                    Roli r = new Roli();
                    String roli = roliCB.getSelectedItem().toString();
                    if (roli.equals("Punetor")) {
                        r.setRoliID(2);
                    } else if (roli.equals("Menaxher")) {
                        r.setRoliID(3);
                    }
                    perdoruesi.setUsername(usernameTxt.getText());
                    perdoruesi.setPassword(new String(passTxt.getPassword()));
                    perdoruesi.setPunetoriID(p);
                    perdoruesi.setRoliID(r);
                    //pr.create(p);
                    perdoruesiRepository.create(perdoruesi);
                    clear();
                } else {
                    JOptionPane.showMessageDialog(null, "Ju lutem kontrolloni fieldat,shenoni parametrat e sakt , dhe mos leni fielda te pa plotesuar");
                }
            } else {

                //EDIT
                usernameTxt.setEditable(false);
                passTxt.setEditable(false);

                if (CheckMismatchTypeEdit() && fieldsValidationEdit()) {
                    Punetori p = ptm.getPersoni(row);
                    ArrayList<Telefoni> telefonNumbers = new ArrayList<>(p.getTelefoniCollection());
                    p.setEmri(emriTxt.getText());
                    p.setMbiemri(mbiemriTxt.getText());
                    p.setDataLindjes(datalindjes.getDate());
                    p.setDataPunesimit(datapunesimit.getDate());
                    p.setEmail(emailTxt.getText());
                    p.setQyteti(qytetiTxt.getText());
                    p.setAdresa(adresaTxt.getText());
                    p.setDepartmentiId((Departmenti) departmentiCB.getSelectedItem());
                    p.setTitulli((TitulliPunetorit) pozitaCB.getSelectedItem());
                    if (mashkullRadio.isSelected()) {
                        p.setGjinia("M");
                    } else if (femerRadio.isSelected()) {
                        p.setGjinia("F");
                    }
                    Telefoni t = null;
                    if (!telefonNumbers.isEmpty()) {
                        t = telefonNumbers.get(0);
                        t.setTelefoniShtepise(homeTxt.getText());
                        t.setTelefoniBiznesit(biznisTelTxt.getText());
                        t.setTelefoniMobil(telMobilTxt.getText());
                    } else {
                        if (!homeTxt.getText().isEmpty()
                                || !biznisTelTxt.getText().isEmpty() || !telMobilTxt.getText().isEmpty()) {
                            System.out.println("New Telefoni object created");
                            t = new Telefoni();
                            t.setTelefoniShtepise(homeTxt.getText());
                            t.setTelefoniBiznesit(biznisTelTxt.getText());
                            t.setTelefoniMobil(telMobilTxt.getText());
                        }
                    }
                    // Create list and add telefoni
                    if (t != null) {
                        List<Telefoni> numrat = new ArrayList<>();
                        numrat.add(t);
                        p.setTelefoniCollection(numrat);
                        t.setPunetoriId(p);
                    }
                    if (mashkullRadio.isSelected()) {
                        p.setGjinia("M");
                        femerRadio.setSelected(false);
                    } else if (femerRadio.isSelected()) {
                        p.setGjinia("F");
                        mashkullRadio.setSelected(false);
                    }
                    pr.edit(p);
//                tr.edit(t);
                } else {
                    JOptionPane.showMessageDialog(null, "Ju lutem kontrolloni fieldat,shenoni parametrat e sakt , dhe mos leni fielda te pa plotesuar");
                }
            }
            loadTable();
        } catch (EmployeeException ex) {
            JOptionPane.showMessageDialog(this, "E dhena ekziton!");
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        clear();
        usernameTxt.setEditable(true);
        passTxt.setEditable(true);
        usernameTxt.setBackground(new Color(255, 255, 255));
        passTxt.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        int row = table.getSelectedRow();
        if (row != -1) {
            Object[] ob = {"Po", "Jo"};
            int i = JOptionPane.showOptionDialog(this, "A dëshironi te fshihni rekordin ?", "Fshirja",
                    JOptionPane.OK_OPTION, JOptionPane.QUESTION_MESSAGE, null, ob, ob[1]);
            if (i == 0) {
                Punetori p = ptm.getPersoni(row);

                try {
                    pr.delete(p);
                } catch (EmployeeException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }
                clear();
                loadTable();
            } else {
                clear();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Nuk keni selektuar asgje per te fshire!");
        }


    }//GEN-LAST:event_deleteBtnActionPerformed

    private void telMobilTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telMobilTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telMobilTxtActionPerformed

    private void qytetiTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qytetiTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qytetiTxtActionPerformed

    private void mashkullRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mashkullRadioActionPerformed
        // TODO add your handling code here:
        mashkullRadio.setSelected(true);
        femerRadio.setSelected(false);
    }//GEN-LAST:event_mashkullRadioActionPerformed

    private void femerRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femerRadioActionPerformed
        // TODO add your handling code here:
        femerRadio.setSelected(true);
        mashkullRadio.setSelected(false);
    }//GEN-LAST:event_femerRadioActionPerformed

    private void departmentiCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentiCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departmentiCBActionPerformed

    private void usernameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTxtActionPerformed
    }//GEN-LAST:event_usernameTxtActionPerformed

    private void tablePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tablePropertyChange
    }//GEN-LAST:event_tablePropertyChange

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        usernameTxt.setEditable(false);
        passTxt.setEditable(false);
        usernameTxt.setBackground(new Color(177, 187, 204));
        passTxt.setBackground(new Color(177, 187, 204));
    }//GEN-LAST:event_tableMouseClicked

    private void departmentiCBPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_departmentiCBPropertyChange
        // TODO add your handling code here:

    }//GEN-LAST:event_departmentiCBPropertyChange

    private void departmentiCBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_departmentiCBItemStateChanged
        // TODO add your handling code here:
        if (departmentiCB.getSelectedIndex() == 0) {
            loadComboBoxTitulli(1);

        } else if (departmentiCB.getSelectedIndex() == 1) {
            loadComboBoxTitulli(2);
        } else {
            loadComboBoxTitulli(3);
        }
    }//GEN-LAST:event_departmentiCBItemStateChanged

    public void clear() {
        table.clearSelection();
        punetoriIdTxt.setText("");
        emriTxt.setText("");
        mbiemriTxt.setText("");
        emailTxt.setText("");
        homeTxt.setText("");
        biznisTelTxt.setText("");
        adresaTxt.setText("");
        qytetiTxt.setText("");
        datalindjes.setDate(null);
        datapunesimit.setDate(null);
        mashkullRadio.setSelected(false);
        femerRadio.setSelected(false);
        telMobilTxt.setText("");
        biznisTelTxt.setText("");
        homeTxt.setText("");
        departmentiCB.setSelectedIndex(-1);
        departmentiCB.repaint();
        pozitaCB.setSelectedIndex(-1);
        pozitaCB.repaint();
        usernameTxt.setText("");
        passTxt.setText("");
        roliCB.setSelectedIndex(-1);
        roliCB.repaint();

    }

    public void loadComboBox() {
        try {
            List<Departmenti> lista = dr.findAll();
            dcb.add(lista);
            departmentiCB.setModel(dcb);
            departmentiCB.repaint();
        } catch (EmployeeException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

    }

    public void loadComboBoxTitulli(Integer id) {
        try {
            List<TitulliPunetorit> lista = titulliRepository.findByDep(id);
            tcbm.add(lista);
            pozitaCB.setModel(tcbm);
            pozitaCB.repaint();
        } catch (EmployeeException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

    }

    private void tabelaSelectedIndexChange() {
        final ListSelectionModel rowSM = table.getSelectionModel();
        rowSM.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent Ise) {
                if (Ise.getValueIsAdjusting()) {
                    return;
                }
                ListSelectionModel rowSM = (ListSelectionModel) Ise.getSource();
                int selectedIndex = rowSM.getAnchorSelectionIndex();
                if (selectedIndex > -1) {

                    Punetori p = ptm.getPersoni(selectedIndex);
                    ArrayList<Telefoni> telefonNumbers = new ArrayList<>(p.getTelefoniCollection());
                    punetoriIdTxt.setText(p.getPunetoriID().toString());
                    emriTxt.setText(p.getEmri());
                    mbiemriTxt.setText(p.getMbiemri());

                    pozitaCB.repaint();

                    if (p.getGjinia() == "M") {
                        mashkullRadio.setSelected(true);
                        femerRadio.setSelected(false);

                    } else if (p.getGjinia() == "F") {
                        femerRadio.setSelected(true);
                        mashkullRadio.setSelected(false);
                    }
                    dcb.setSelectedItem(p.getDepartmentiId());
                    departmentiCB.repaint();
                    emailTxt.setText(p.getEmail());
                    tcbm.setSelectedItem(p.getTitulli());
                    pozitaCB.repaint();
                    adresaTxt.setText(p.getAdresa());
                    qytetiTxt.setText(p.getQyteti());
                    datapunesimit.setDate(p.getDataPunesimit());
                    datalindjes.setDate(p.getDataLindjes());

                    int roli = p.getPerdoruesi().getRoliID().getRoliID();
                    if (roli == 2) {
                        roliCB.setSelectedIndex(0);
                    } else if (roli == 3) {
                        roliCB.setSelectedIndex(1);
                    }
                    if (telefonNumbers.size() >= 1) {
                        Telefoni t = telefonNumbers.get(0);
                        homeTxt.setText(t.getTelefoniShtepise());
                        biznisTelTxt.setText(t.getTelefoniBiznesit());
                        telMobilTxt.setText(t.getTelefoniMobil());
                    } else {
                        homeTxt.setText("");
                        biznisTelTxt.setText("");
                        telMobilTxt.setText("");
                    }

                }
            }
        });
    }

    public void loadTable() {
        try {
            List<Punetori> lista = pr.findOnlyEmployees();

            List<Telefoni> lista_tel = tr.findAll();
            ptm.addList(lista, lista_tel);
            table.setModel(ptm);
            ptm.fireTableDataChanged();
        } catch (EmployeeException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    //VALIDATION
    public boolean CheckMismatchType() {
        if (!emriTxt.getText().matches("[a-zA-Z',\\s]*") || !mbiemriTxt.getText().matches("[a-zA-Z',\\s]*")
                || !qytetiTxt.getText().matches("[a-zA-Z',\\s]*")
                || !adresaTxt.getText().matches("[a-zA-Z',\\s]*")
                || !emailTxt.getText().matches("^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$")) {
            return false;
        } else {
            return true;
        }
    }

    public boolean CheckMismatchTypeEdit() {
        if (!emriTxt.getText().matches("[a-zA-Z',\\s]*") || !mbiemriTxt.getText().matches("[a-zA-Z',\\s]*")
                || !qytetiTxt.getText().matches("[a-zA-Z',\\s]*")
                || !adresaTxt.getText().matches("[a-zA-Z',\\s]*")
                || !emailTxt.getText().matches("^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$")) {
            return false;
        } else {
            return true;
        }
    }

    public boolean fieldsValidationEdit() {
        if (emriTxt.getText().isEmpty() || mbiemriTxt.getText().isEmpty() || emailTxt.getText().isEmpty()
                || homeTxt.getText().isEmpty() || qytetiTxt.getText().isEmpty() || adresaTxt.getText().isEmpty()
                || datapunesimit.getDate() == null || datalindjes.getDate() == null
                || departmentiCB.getSelectedItem() == null || pozitaCB.getSelectedItem() == null || roliCB.getSelectedItem() == null) {
            return false;
        } else {
            return true;
        }
    }

    public boolean fieldsValidation() {
        if (emriTxt.getText().isEmpty() || mbiemriTxt.getText().isEmpty() || emailTxt.getText().isEmpty()
                || homeTxt.getText().isEmpty() || qytetiTxt.getText().isEmpty() || adresaTxt.getText().isEmpty()
                || datapunesimit.getDate() == null || datalindjes.getDate() == null || usernameTxt.getText().isEmpty()
                || departmentiCB.getSelectedItem() == null || pozitaCB.getSelectedItem() == null || roliCB.getSelectedItem() == null) {
            return false;
        } else {
            return true;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adresaTxt;
    private javax.swing.JTextField biznisTelTxt;
    private javax.swing.JButton cancelBtn;
    private com.toedter.calendar.JDateChooser datalindjes;
    private com.toedter.calendar.JDateChooser datapunesimit;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JComboBox departmentiCB;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JTextField emriTxt;
    private javax.swing.JRadioButton femerRadio;
    private javax.swing.JTextField homeTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton mashkullRadio;
    private javax.swing.JTextField mbiemriTxt;
    private javax.swing.JPasswordField passTxt;
    private javax.swing.JComboBox pozitaCB;
    private javax.swing.JTextField punetoriIdTxt;
    private javax.swing.JTextField qytetiTxt;
    private javax.swing.JComboBox<String> roliCB;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTable table;
    private javax.swing.JTextField telMobilTxt;
    private javax.swing.JTextField usernameTxt;
    // End of variables declaration//GEN-END:variables
}
