/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.view;

import BL.EmployeeException;
import BL.VerejtjaRepository;
import DAL.Verejtja;
import gui.model.VerejtjaTableModel;
import static gui.view.VleresoPunetorin.v;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author MR-ROBOT
 */
public class PunetoriVerejtjaForm extends javax.swing.JInternalFrame {

    VerejtjaRepository vr = new VerejtjaRepository();
    VerejtjaTableModel vtm = new VerejtjaTableModel();
    int id = Emp.empId;
    VerejtjaFormData vfd = new VerejtjaFormData();

    /**
     * Creates new form PunetoriAnkesatForm
     */
    public PunetoriVerejtjaForm() throws EmployeeException {
        if (vr.findVerejtjaPerdoruesi(id).size() == 0) {
            JOptionPane.showMessageDialog(null, "Nuk keni asnje verejtje deri me tani");
        } else {
            initComponents();
            loadTable();
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ankesaLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setClosable(true);

        ankesaLbl.setForeground(new java.awt.Color(0, 204, 0));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(ankesaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 917, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(82, 82, 82))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(ankesaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
              try {
            // TODO add your handling code here:
            // TODO add your handling code here:
            int index = table.getSelectedRow();
            SimpleDateFormat format = new SimpleDateFormat("dd-MM-yyyy");

            TableModel model = table.getModel();
            String id = model.getValueAt(index, 0).toString();
            int x = Integer.parseInt(id);
            v = vr.findByID(x);
            vfd.emriTxt.setText(v.getEmriPunetorit() + " " + v.getMbiemriPunetorit());
            vfd.titulliTxt.setText(v.getTitulliRastit());
            vfd.verejtaNgaTxt.setText(v.getKrijuarNga());
            vfd.pershkrimiTxt.setText(v.getPershkrimi());
            vfd.setVisible(true);
            vfd.setLocationRelativeTo(null);
            vfd.pack();
            vfd.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            vfd.dataRastit.setDate(v.getData());
            vfd.jButton1.setVisible(false);
            vfd.jButton3.setVisible(false);
            
        } catch (EmployeeException ex) {
            Logger.getLogger(VleresoPunetorin.class.getName()).log(Level.SEVERE, null, ex);
        }
        loadTable();
    }//GEN-LAST:event_tableMouseClicked

    public void loadTable() {
        try {
            List<Verejtja> lista = vr.findVerejtjaPerdoruesi(id);
            System.out.println(lista.size());
            vtm.addList(lista);
            table.setModel(vtm);
            vtm.fireTableDataChanged();
        } catch (EmployeeException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ankesaLbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

}
