/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.view;

import BL.DConnection;
import BL.EmployeeException;
import BL.PerdoruesiRepository;
import BL.PushimiPunetoriRepository;
import DAL.Perdoruesi;
import DAL.Punetori;
import DAL.Pushimi;
import DAL.PushimiPunetori;
import DAL.Telefoni;
import gui.model.PerdoruesiComboBoxModel;
import gui.model.PushimiPunetoriTableModel;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import static org.codehaus.groovy.runtime.DefaultGroovyMethods.tr;

/**
 *
 * @author MR-ROBOT
 */
public class PushimetEKerkuaraForm extends javax.swing.JInternalFrame {

    DConnection source = new DConnection();
    PushimiPunetoriTableModel pptm = new PushimiPunetoriTableModel();
    PushimiPunetoriRepository ppr = new PushimiPunetoriRepository();
    PerdoruesiRepository pr = new PerdoruesiRepository();
    PerdoruesiComboBoxModel pcbm = new PerdoruesiComboBoxModel();

    /**
     * Creates new form PushimetEKerkuaraForm
     */
    public PushimetEKerkuaraForm() {
        initComponents();
        loadComboBox();

    }

    public void loadTable() throws EmployeeException {
        List<PushimiPunetori> lista;
        if (perdoruesiCB.getSelectedIndex() != -1) {
            Perdoruesi perdoruesi = (Perdoruesi) perdoruesiCB.getSelectedItem();
            lista = ppr.findByID(perdoruesi.getPerdoruesiID());
        } else {
            lista = ppr.findAll();
        }
        pptm.addList(lista);
        table.setModel(pptm);
        pptm.fireTableDataChanged();
    }

    public void loadComboBox() {
        try {
            List<Perdoruesi> lista = pr.findExceptAdmin();
            pcbm.add(lista);
            perdoruesiCB.setModel(pcbm);
            perdoruesiCB.repaint();
        } catch (EmployeeException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        zgjidhCB = new javax.swing.JComboBox<>();
        perdoruesiCB = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 164, 1000, 243));

        jButton1.setText("Gjenero");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 59, 113, 40));

        zgjidhCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Te gjitheve", "Punetor te caktuar" }));
        zgjidhCB.setSelectedIndex(-1);
        zgjidhCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                zgjidhCBItemStateChanged(evt);
            }
        });
        getContentPane().add(zgjidhCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 23, 196, -1));

        perdoruesiCB.setToolTipText("");
        getContentPane().add(perdoruesiCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 69, 196, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Zgjidhni Punetorin:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 71, -1, -1));

        jLabel6.setText("Dergo tek:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 26, -1, -1));

        jButton2.setText("Shfaq");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 59, 87, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void zgjidhCBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_zgjidhCBItemStateChanged
        // TODO add your handling code here:
        if (zgjidhCB.getSelectedIndex() == 1) {
            perdoruesiCB.setVisible(true);
            jLabel1.setVisible(true);

        } else if (zgjidhCB.getSelectedIndex() == 0) {
            perdoruesiCB.setVisible(false);
            jLabel1.setVisible(false);
            perdoruesiCB.setSelectedItem(null);
        }
    }//GEN-LAST:event_zgjidhCBItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            loadTable();
        } catch (EmployeeException ex) {
            Logger.getLogger(PushimetEKerkuaraForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    public void ReportTemplateDepartmenti(String SqlStatement, String path) {
        try {

            JasperDesign jd = JRXmlLoader.load(path);
            JRDesignQuery query = new JRDesignQuery();
            query.setText(SqlStatement);
            jd.setQuery(query);
            JasperReport jr = JasperCompileManager.compileReport(jd);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, source.getConnection());
            JasperViewer.viewReport(jp, false);
        } catch (JRException e) {
            e.printStackTrace();
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String sql = "";
        String path = "";
        Perdoruesi p;
        if (perdoruesiCB.getSelectedIndex() == -1) {
            sql = "Select * from Pushimi_Punetori p Inner join Perdoruesi pr on pr.PerdoruesiID=p.perdoruesiID Inner join Punetori pune on pune.punetoriID=pr.punetoriID Inner join Pushimi pu on p.pushimiID=pu.pushimiID";

            path = "C:\\Users\\MR-ROBOT\\Desktop\\currproj\\EmployeeManagmentSystem\\src\\reports\\PushimiPunetoriReports.jrxml";
        } else {

            p = (Perdoruesi) perdoruesiCB.getSelectedItem();
            int pa = p.getPerdoruesiID();
            sql = "Select * from Pushimi_Punetori p Inner join Perdoruesi pr on pr.PerdoruesiID=p.perdoruesiID Inner join Punetori pune on pune.punetoriID=pr.punetoriID Inner join Pushimi pu on p.pushimiID=pu.pushimiID WHERE pr.PerdoruesiID=" + pa;
            path = "C:\\Users\\MR-ROBOT\\Desktop\\currproj\\EmployeeManagmentSystem\\src\\reports\\PushimiPunetoriReports.jrxml";
        }

        ReportTemplateDepartmenti(sql, path);


    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JComboBox perdoruesiCB;
    private javax.swing.JTable table;
    private javax.swing.JComboBox<String> zgjidhCB;
    // End of variables declaration//GEN-END:variables
}
